"":
  with_subcorticalblock: False
standard:
  with_subcorticalblock: True
  colors_p_cells: [r/g, g/r, b/y]
  p_channels: 3
  m_channels: 1
  subcort_noise_mode: neuronal
  gabor_color_prob: [.25,.25,.25,.25]
  vone_k_exc: 5.3
  vone_fano_factor: 0.93
  with_light_adapt: True
  with_contrast_norm: True
  light_adapt_threshold: False
  lgn_to_v2: False
no-p-cells:
  with_subcorticalblock: True
  colors_p_cells: []
  p_channels: 0
  m_channels: 1
  subcort_noise_mode: neuronal
  gabor_color_prob: [1.]
  vone_k_exc: 4.8
  vone_fano_factor: .94
  with_light_adapt: True
  with_contrast_norm: True
  light_adapt_threshold: False
  lgn_to_v2: False
no-m-cells:
  with_subcorticalblock: True
  colors_p_cells: [r/g, g/r, b/y]
  p_channels: 3
  m_channels: 0
  subcort_noise_mode: neuronal
  gabor_color_prob: [.34,.34,.32]
  vone_k_exc: 4.5
  vone_fano_factor: 0.94
  with_light_adapt: True
  with_contrast_norm: True
  light_adapt_threshold: False
  lgn_to_v2: False
no-light-adapt:
  with_subcorticalblock: True
  colors_p_cells: [r/g, g/r, b/y]
  p_channels: 3
  m_channels: 1
  subcort_noise_mode: neuronal
  gabor_color_prob: [.25,.25,.25,.25]
  vone_k_exc: 4.7
  vone_fano_factor: .93
  with_light_adapt: False
  with_contrast_norm: True
  light_adapt_threshold: False
  lgn_to_v2: False
no-contrast-norm:
  with_subcorticalblock: True
  colors_p_cells: [r/g, g/r, b/y]
  p_channels: 3
  m_channels: 1
  subcort_noise_mode: neuronal
  gabor_color_prob: [.25,.25,.25,.25]
  vone_k_exc: 3.2
  vone_fano_factor: .96
  with_light_adapt: True
  with_contrast_norm: False
  light_adapt_threshold: True
  lgn_to_v2: False
no-noise:
  with_subcorticalblock: True
  colors_p_cells: [r/g, g/r, b/y]
  p_channels: 3
  m_channels: 1
  subcort_noise_mode: None
  gabor_color_prob: [.25,.25,.25,.25]
  vone_k_exc: 5.3
  vone_fano_factor: 1
  with_light_adapt: True
  with_contrast_norm: True
  light_adapt_threshold: False
  lgn_to_v2: False
lgn-v2-connection:
  with_subcorticalblock: True
  colors_p_cells: [r/g, g/r, b/y]
  p_channels: 3
  m_channels: 1
  subcort_noise_mode: neuronal
  gabor_color_prob: [.25,.25,.25,.25]
  vone_k_exc: 5.3
  vone_fano_factor: 0.93
  with_light_adapt: True
  with_contrast_norm: True
  light_adapt_threshold: False
  lgn_to_v2: True